media: "src/assets/images"

content:
  - name: art-gallery
    label: Art Gallery
    type: collection
    path: src/content/art-gallery
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: code
      - name: image
        label: Artwork Image
        type: image
        required: true

